insert into user (`id`, `login_id`, `name`, `login_pw`, `role`, `created_at`, `updated_at`, `approved`) values (1, 'dldbwls', 'test', '{bcrypt}$2a$10$d3QK7jlUd8NI6EdHmILzfejSoF.XSlmT/eRdb9zaXuM8YuWmTdzSO', 'boss', now(), now(), 'ACCEPTED');

insert into announce(`id`, `user_id`, `title`, `context`, `img_url`, `view_count`, `updated_at`) values(0, 1, 'test1', 'test1', 'test1', 1, now());
insert into announce(`id`, `user_id`, `title`, `context`, `img_url`, `view_count`, `updated_at`) values(1, 1, 'test1', 'test1', 'test1', 2, now());
insert into announce(`id`, `user_id`, `title`, `context`, `img_url`, `view_count`, `updated_at`) values(2, 1, 'test1', 'test1', 'test1', 3, now());
insert into announce(`id`, `user_id`, `title`, `context`, `img_url`, `view_count`, `updated_at`) values(3, 1, 'test1', 'test1', 'test1', 4, now());
insert into announce(`id`, `user_id`, `title`, `context`, `img_url`, `view_count`, `updated_at`) values(4, 1, 'test1', 'test1', 'test1', 5, now());
insert into announce(`id`, `user_id`, `title`, `context`, `img_url`, `view_count`, `updated_at`) values(5, 1, 'test1', 'test1', 'test1', 6, now());
insert into announce(`id`, `user_id`, `title`, `context`, `img_url`, `view_count`, `updated_at`) values(6, 1, 'test1', 'test1', 'test1', 7, now());
insert into announce(`id`, `user_id`, `title`, `context`, `img_url`, `view_count`, `updated_at`) values(7, 1, 'test1', 'test1', 'test1', 8, now());
insert into announce(`id`, `user_id`, `title`, `context`, `img_url`, `view_count`, `updated_at`) values(8, 1, 'test1', 'test1', 'test1', 9, now());
insert into announce(`id`, `user_id`, `title`, `context`, `img_url`, `view_count`, `updated_at`) values(9, 1, 'test1', 'test1', 'test1', 10, now());
insert into announce(`id`, `user_id`, `title`, `context`, `img_url`, `view_count`, `updated_at`) values(10, 1, 'test1', 'test1', 'test1', 11, now());
insert into announce(`id`, `user_id`, `title`, `context`, `img_url`, `view_count`, `updated_at`) values(11, 1, 'test1', 'test1', 'test1', 12, now());
insert into announce(`id`, `user_id`, `title`, `context`, `img_url`, `view_count`, `updated_at`) values(12, 1, 'test1', 'test1', 'test1', 13, now());
insert into announce(`id`, `user_id`, `title`, `context`, `img_url`, `view_count`, `updated_at`) values(13, 1, 'test1', 'test1', 'test1', 14, now());
insert into announce(`id`, `user_id`, `title`, `context`, `img_url`, `view_count`, `updated_at`) values(14, 1, 'test1', 'test1', 'test1', 15, now());
insert into announce(`id`, `user_id`, `title`, `context`, `img_url`, `view_count`, `updated_at`) values(15, 1, 'test1', 'test1', 'test1', 16, now());
insert into announce(`id`, `user_id`, `title`, `context`, `img_url`, `view_count`, `updated_at`) values(16, 1, 'test1', 'test1', 'test1', 17, now());
insert into announce(`id`, `user_id`, `title`, `context`, `img_url`, `view_count`, `updated_at`) values(17, 1, 'test1', 'test1', 'test1', 18, now());
